package com.learning.familytree;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {
        CommandRegexAnnotationProcessor processor = new CommandRegexAnnotationProcessor(new FamilyTree());
//        processor.printMethods();
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
        for(;;) {
            String line = reader.readLine();
            if(line!=null && line!="") {
                processor.parseCommand(line);
            }
        }
    }
}
